CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Auditorias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Accion" text NOT NULL,
        "Entidad" text NOT NULL,
        "Detalle" text NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Auditorias" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Notificaciones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Tipo" text NOT NULL,
        "Destino" text NOT NULL,
        "Mensaje" text NOT NULL,
        "FechaEnvio" date NOT NULL,
        "Enviado" boolean NOT NULL,
        CONSTRAINT "PK_Notificaciones" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Planes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Descripcion" text NOT NULL,
        "Precio" numeric NOT NULL,
        "DuracionDias" integer NOT NULL,
        "MaxReservasPorMes" integer,
        "TiposPermitidos" text,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Planes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Sucursales" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Direccion" text NOT NULL,
        "Telefono" text NOT NULL,
        "Email" text NOT NULL,
        "Activa" boolean NOT NULL,
        CONSTRAINT "PK_Sucursales" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Salas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SucursalId" integer NOT NULL,
        "Nombre" text NOT NULL,
        "Tipo" text NOT NULL,
        "Capacidad" integer NOT NULL,
        "Descripcion" text NOT NULL,
        "Activa" boolean NOT NULL,
        CONSTRAINT "PK_Salas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Salas_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        "Apellido" text NOT NULL,
        "Dni" text NOT NULL,
        "Email" text NOT NULL,
        "Telefono" text NOT NULL,
        "FechaNacimiento" date NOT NULL,
        "Genero" text,
        "Direccion" text,
        "Image" text,
        "SucursalId" integer,
        "PlanId" integer,
        "Activo" boolean NOT NULL,
        "FailedLoginAttempts" integer NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "Discriminator" character varying(8) NOT NULL,
        "Especialidad" text,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Usuarios_Planes_PlanId" FOREIGN KEY ("PlanId") REFERENCES "Planes" ("Id"),
        CONSTRAINT "FK_Usuarios_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Clases" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProfesorId" integer NOT NULL,
        "SalaId" integer NOT NULL,
        "SucursalId" integer NOT NULL,
        "Nombre" text NOT NULL,
        "Descripcion" text NOT NULL,
        "Imagen" text,
        "Tipo" text,
        "DuracionMinutos" integer NOT NULL,
        "HoraInicio" time without time zone NOT NULL,
        "Fecha" date NOT NULL,
        "Dias" text,
        "Capacidad" integer NOT NULL,
        "MostrarEnHome" boolean NOT NULL,
        "Activa" boolean NOT NULL,
        CONSTRAINT "PK_Clases" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Clases_Salas_SalaId" FOREIGN KEY ("SalaId") REFERENCES "Salas" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Clases_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Clases_Usuarios_ProfesorId" FOREIGN KEY ("ProfesorId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Membresias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AlumnoId" integer NOT NULL,
        "PlanId" integer NOT NULL,
        "FechaInicio" date NOT NULL,
        "FechaFin" date NOT NULL,
        "Activa" boolean NOT NULL,
        CONSTRAINT "PK_Membresias" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Membresias_Planes_PlanId" FOREIGN KEY ("PlanId") REFERENCES "Planes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Membresias_Usuarios_AlumnoId" FOREIGN KEY ("AlumnoId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Reservas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AlumnoId" integer NOT NULL,
        "ClaseId" integer NOT NULL,
        "FechaReserva" date NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Reservas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reservas_Clases_ClaseId" FOREIGN KEY ("ClaseId") REFERENCES "Clases" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reservas_Usuarios_AlumnoId" FOREIGN KEY ("AlumnoId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE TABLE "Pagos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MembresiaId" integer NOT NULL,
        "Monto" numeric NOT NULL,
        "FechaPago" date NOT NULL,
        "FechaVencimiento" date NOT NULL,
        "MetodoPago" text NOT NULL,
        "Estado" boolean NOT NULL,
        CONSTRAINT "PK_Pagos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pagos_Membresias_MembresiaId" FOREIGN KEY ("MembresiaId") REFERENCES "Membresias" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Clases_ProfesorId" ON "Clases" ("ProfesorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Clases_SalaId" ON "Clases" ("SalaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Clases_SucursalId" ON "Clases" ("SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Membresias_AlumnoId" ON "Membresias" ("AlumnoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Membresias_PlanId" ON "Membresias" ("PlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Pagos_MembresiaId" ON "Pagos" ("MembresiaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Reservas_AlumnoId" ON "Reservas" ("AlumnoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Reservas_ClaseId" ON "Reservas" ("ClaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Salas_SucursalId" ON "Salas" ("SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Usuarios_PlanId" ON "Usuarios" ("PlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    CREATE INDEX "IX_Usuarios_SucursalId" ON "Usuarios" ("SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217021906_InitialStructureClean') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251217021906_InitialStructureClean', '8.0.5');
    END IF;
END $EF$;
COMMIT;

