// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20251127051911_ActualizarUsuarioSeedData")]
    partial class ActualizarUsuarioSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dias")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MostrarEnHome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SucursalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("SalaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Clases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Capacidad = 15,
                            Descripcion = "Clase suave para activar el cuerpo y la mente. Ideal para empezar el día con energía.",
                            Dias = "[\"Lunes\",\"Miércoles\",\"Viernes\"]",
                            DuracionMinutos = 60,
                            Fecha = new DateOnly(2025, 10, 11),
                            HoraInicio = new TimeOnly(0, 0, 0),
                            Imagen = "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
                            MostrarEnHome = true,
                            Nombre = "Yoga Matinal",
                            ProfesorId = 2,
                            SalaId = 1,
                            SucursalId = 1,
                            Tipo = "general"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Capacidad = 20,
                            Descripcion = "Entrenamiento cardiovascular sobre bicicletas fijas, con música y mucha energía.",
                            Dias = "[\"Martes\",\"Jueves\",\"Sábado\"]",
                            DuracionMinutos = 60,
                            Fecha = new DateOnly(2025, 10, 10),
                            HoraInicio = new TimeOnly(18, 0, 0),
                            Imagen = "https://images.pexels.com/photos/4853854/pexels-photo-4853854.jpeg",
                            MostrarEnHome = true,
                            Nombre = "Spin Intenso",
                            ProfesorId = 2,
                            SalaId = 2,
                            SucursalId = 2,
                            Tipo = "general"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Capacidad = 18,
                            Descripcion = "Sesiones de alta intensidad con pesas, cardio y fuerza funcional.",
                            Dias = "[\"Lunes\",\"Martes\",\"Jueves\"]",
                            DuracionMinutos = 60,
                            Fecha = new DateOnly(2025, 10, 11),
                            HoraInicio = new TimeOnly(17, 0, 0),
                            Imagen = "https://images.pexels.com/photos/7674492/pexels-photo-7674492.jpeg",
                            MostrarEnHome = true,
                            Nombre = "CrossFit Power",
                            ProfesorId = 3,
                            SalaId = 3,
                            SucursalId = 3,
                            Tipo = "especializada"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Capacidad = 12,
                            Descripcion = "Fortalecé tu zona media con ejercicios controlados y precisos.",
                            Dias = "[\"Miércoles\",\"Viernes\"]",
                            DuracionMinutos = 60,
                            Fecha = new DateOnly(2025, 10, 12),
                            HoraInicio = new TimeOnly(13, 0, 0),
                            Imagen = "https://images.pexels.com/photos/3775524/pexels-photo-3775524.jpeg",
                            MostrarEnHome = true,
                            Nombre = "Pilates Core",
                            ProfesorId = 4,
                            SalaId = 4,
                            SucursalId = 1,
                            Tipo = "general"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Capacidad = 16,
                            Descripcion = "Entrenamiento completo en 45 minutos. Ideal para quienes tienen poco tiempo.",
                            Dias = "[\"Martes\",\"Jueves\"]",
                            DuracionMinutos = 45,
                            Fecha = new DateOnly(2025, 10, 12),
                            HoraInicio = new TimeOnly(13, 0, 0),
                            Imagen = "https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg",
                            MostrarEnHome = false,
                            Nombre = "Funcional Express",
                            ProfesorId = 5,
                            SalaId = 5,
                            SucursalId = 2,
                            Tipo = "general"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Capacidad = 25,
                            Descripcion = "Baile, energía y diversión. Quemás calorías sin darte cuenta.",
                            Dias = "[\"Lunes\",\"Miércoles\",\"Sábado\"]",
                            DuracionMinutos = 60,
                            Fecha = new DateOnly(2025, 10, 12),
                            HoraInicio = new TimeOnly(19, 0, 0),
                            Imagen = "https://images.pexels.com/photos/8436601/pexels-photo-8436601.jpeg",
                            MostrarEnHome = false,
                            Nombre = "Zumba Party",
                            ProfesorId = 6,
                            SalaId = 6,
                            SucursalId = 3,
                            Tipo = "general"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Capacidad = 14,
                            Descripcion = "Ideal para la recuperación muscular y la relajación post entrenamiento.",
                            Dias = "[\"Miércoles\",\"Viernes\",\"Domingo\"]",
                            DuracionMinutos = 60,
                            Fecha = new DateOnly(2025, 10, 13),
                            HoraInicio = new TimeOnly(20, 0, 0),
                            Imagen = "https://images.pexels.com/photos/3076509/pexels-photo-3076509.jpeg",
                            MostrarEnHome = false,
                            Nombre = "Stretch & Relax",
                            ProfesorId = 7,
                            SalaId = 7,
                            SucursalId = 1,
                            Tipo = "general"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Membresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("PlanId");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enviado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembresiaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxReservasPorMes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("TiposPermitidos")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Acceso a clases generales y recursos introductorios. Ideal para quienes recién comienzan.",
                            DuracionDias = 30,
                            MaxReservasPorMes = 8,
                            Nombre = "Básico",
                            Precio = 25000m,
                            TiposPermitidos = "[\"general\"]"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Incluye acceso a clases especializadas, soporte prioritario y material exclusivo.",
                            DuracionDias = 30,
                            MaxReservasPorMes = 20,
                            Nombre = "Avanzado",
                            Precio = 40000m,
                            TiposPermitidos = "[]"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Acceso ilimitado a todos los cursos, mentorías personalizadas y beneficios exclusivos.",
                            DuracionDias = 30,
                            Nombre = "Premium",
                            Precio = 55000m,
                            TiposPermitidos = "[]"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaReserva")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ClaseId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SucursalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Capacidad = 25,
                            Descripcion = "Sala multiuso para yoga, pilates y actividades grupales",
                            Nombre = "Sala A",
                            SucursalId = 1,
                            Tipo = "Multiuso"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Capacidad = 20,
                            Descripcion = "Sala equipada con 20 bicicletas estáticas profesionales",
                            Nombre = "Sala B",
                            SucursalId = 1,
                            Tipo = "Spinning"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Capacidad = 30,
                            Descripcion = "Espacio amplio para entrenamiento funcional y crossfit",
                            Nombre = "Sala 1",
                            SucursalId = 2,
                            Tipo = "Funcional"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Capacidad = 40,
                            Descripcion = "Sala de musculación con equipamiento completo",
                            Nombre = "Sala 2",
                            SucursalId = 2,
                            Tipo = "Pesas"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Capacidad = 22,
                            Descripcion = "Sala de cardio con equipamiento variado",
                            Nombre = "Sala 5",
                            SucursalId = 2,
                            Tipo = "Cardio"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Capacidad = 30,
                            Descripcion = "Espacio amplio para clases de baile y zumba",
                            Nombre = "Sala 6",
                            SucursalId = 3,
                            Tipo = "Baile"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Capacidad = 18,
                            Descripcion = "Estudio pequeño para sesiones especializadas",
                            Nombre = "Sala 7",
                            SucursalId = 1,
                            Tipo = "Estudio"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Direccion = "Av. Principal 123",
                            Email = "centro@gym.com",
                            Nombre = "Sucursal Centro",
                            Telefono = "555-0001"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Direccion = "Calle Norte 456",
                            Email = "norte@gym.com",
                            Nombre = "Sucursal Norte",
                            Telefono = "555-0002"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Direccion = "Av. Sur 789",
                            Email = "sur@gym.com",
                            Nombre = "Sucursal Sur",
                            Telefono = "555-0003"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = -9999,
                            Activo = true,
                            Apellido = "User",
                            Direccion = "Sede Central, Admin St 101",
                            Discriminator = "Usuario",
                            Dni = "00000000",
                            Email = "admin@gym.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1990, 1, 1),
                            Genero = "No especificado",
                            Image = "https://placehold.co/120x120?text=Admin",
                            Nombre = "Admin",
                            PasswordHash = "R7n4G/D8mUoF9g01/M8t4gH1cO4v5xT2zS0l+L4nI3q7kP9wJ0yT+uF0xV8aC2bF",
                            Role = "Administrador",
                            SucursalId = 1,
                            Telefono = "555-9999"
                        },
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Santarelli",
                            Direccion = "Av. Siempre Viva 742",
                            Discriminator = "Usuario",
                            Dni = "1",
                            Email = "simon@example.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(2005, 3, 12),
                            Genero = "Masculino",
                            Image = "https://placehold.co/120x120?text=SuperAdmin",
                            Nombre = "Simón",
                            PasswordHash = "HfLlcoG+fBtUcKKRzzb3sTcc0Kk1P0qAGDSXV656AFKkzPJ5tGWmtiXdOVLmMjT7",
                            Role = "SuperAdministrador",
                            SucursalId = 1,
                            Telefono = "3411234567"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellido = "González",
                            Direccion = "Calle Falsa 123",
                            Discriminator = "Profesor",
                            Dni = "11111111",
                            Email = "maria.profe@gym.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1985, 6, 12),
                            Genero = "Femenino",
                            Image = "https://placehold.co/120x120?text=Maria",
                            Nombre = "María",
                            PasswordHash = "s+LhM8wzY1QxK2n0tN7q5wX2yC4aA8bC9dE0fG3hJ6p8rT4uV7yZ2eB3eD5gH0iK",
                            Role = "Profesor",
                            SucursalId = 1,
                            Telefono = "555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellido = "Pérez",
                            Direccion = "Av. Rivadavia 800",
                            Discriminator = "Profesor",
                            Dni = "22222222",
                            Email = "carlos.profe@gym.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1980, 3, 2),
                            Genero = "Masculino",
                            Image = "https://placehold.co/120x120?text=Carlos",
                            Nombre = "Carlos",
                            PasswordHash = "s+LhM8wzY1QxK2n0tN7q5wX2yC4aA8bC9dE0fG3hJ6p8rT4uV7yZ2eB3eD5gH0iK",
                            Role = "Profesor",
                            SucursalId = 2,
                            Telefono = "555-1003"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellido = "Ramírez",
                            Direccion = "Calle 9 de Julio 50",
                            Discriminator = "Profesor",
                            Dni = "33333333",
                            Email = "lucia.profe@gym.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1990, 11, 5),
                            Genero = "Femenino",
                            Image = "https://placehold.co/120x120?text=Lucia",
                            Nombre = "Lucía",
                            PasswordHash = "s+LhM8wzY1QxK2n0tN7q5wX2yC4aA8bC9dE0fG3hJ6p8rT4uV7yZ2eB3eD5gH0iK",
                            Role = "Profesor",
                            SucursalId = 1,
                            Telefono = "555-1004"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellido = "Suárez",
                            Direccion = "Boulevard Oroño 1500",
                            Discriminator = "Profesor",
                            Dni = "44444444",
                            Email = "martin.profe@gym.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1988, 8, 20),
                            Genero = "Masculino",
                            Image = "https://placehold.co/120x120?text=Martin",
                            Nombre = "Martín",
                            PasswordHash = "s+LhM8wzY1QxK2n0tN7q5wX2yC4aA8bC9dE0fG3hJ6p8rT4uV7yZ2eB3eD5gH0iK",
                            Role = "Profesor",
                            SucursalId = 2,
                            Telefono = "555-1005"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apellido = "López",
                            Direccion = "Pasaje Zeballos 33",
                            Discriminator = "Profesor",
                            Dni = "55555555",
                            Email = "sofia.profe@gym.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1992, 2, 14),
                            Genero = "Femenino",
                            Image = "https://placehold.co/120x120?text=Sofia",
                            Nombre = "Sofía",
                            PasswordHash = "s+LhM8wzY1QxK2n0tN7q5wX2yC4aA8bC9dE0fG3hJ6p8rT4uV7yZ2eB3eD5gH0iK",
                            Role = "Profesor",
                            SucursalId = 3,
                            Telefono = "555-1006"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apellido = "Fernández",
                            Direccion = "Ruta 9 KM 10",
                            Discriminator = "Profesor",
                            Dni = "66666666",
                            Email = "diego.profe@gym.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1983, 9, 30),
                            Genero = "Masculino",
                            Image = "https://placehold.co/120x120?text=Diego",
                            Nombre = "Diego",
                            PasswordHash = "s+LhM8wzY1QxK2n0tN7q5wX2yC4aA8bC9dE0fG3hJ6p8rT4uV7yZ2eB3eD5gH0iK",
                            Role = "Profesor",
                            SucursalId = 1,
                            Telefono = "555-1007"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Apellido = "Cumini",
                            Direccion = "Calle San Martín 1500",
                            Discriminator = "Usuario",
                            Dni = "39222001",
                            Email = "fran@highfit.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1995, 5, 20),
                            Genero = "Masculino",
                            Image = "https://placehold.co/120x120?text=AdminFran",
                            Nombre = "Francisco",
                            PasswordHash = "+yFOjDzWtkAR9lxanKPZsbY3Na3Kv5ZrRBOpG0nJfBt7YFf/LJurnWJrskA6QWT8",
                            Role = "Administrador",
                            SucursalId = 1,
                            Telefono = "3412345678"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Apellido = "Cardillo",
                            Direccion = "Av. Pellegrini 200",
                            Discriminator = "Usuario",
                            Dni = "39555111",
                            Email = "pablo@highfit.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1996, 10, 3),
                            Genero = "Masculino",
                            Image = "https://placehold.co/120x120?text=Recep",
                            Nombre = "Pablo",
                            PasswordHash = "hz5yIy4nK3ZmVcTPJki6YH0sTq3debyK804lrYE+bqI0Fgz7i/PXysORUKzjBtGH",
                            Role = "Recepcionista",
                            SucursalId = 1,
                            Telefono = "3413456789"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Apellido = "Perez",
                            Direccion = "Bv. 27 de Febrero 100",
                            Discriminator = "Alumno",
                            Dni = "40111222",
                            Email = "cliente@demo.com",
                            FailedLoginAttempts = 0,
                            FechaNacimiento = new DateOnly(1997, 4, 1),
                            Genero = "Masculino",
                            Image = "https://placehold.co/120x120?text=Cliente",
                            Nombre = "Cliente Demo",
                            PasswordHash = "FNnfcvojVZDEjAzKc+6S3aD0QOHlc0vd6lIRLQ7Nt1pYxgP/TtcZvobB9F/gp+vO",
                            PlanId = 2,
                            Role = "Alumno",
                            SucursalId = 1,
                            Telefono = "+5493415555555"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Alumno", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Alumno");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.Property<string>("Especialidad")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.HasOne("Domain.Entities.Profesor", "Profesor")
                        .WithMany("Clases")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sala", "Sala")
                        .WithMany("Clases")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Clases")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");

                    b.Navigation("Sala");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Domain.Entities.Membresia", b =>
                {
                    b.HasOne("Domain.Entities.Alumno", "Alumno")
                        .WithMany("Membresias")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Plan", "Plan")
                        .WithMany("Membresias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.HasOne("Domain.Entities.Membresia", "Membresia")
                        .WithMany("Pagos")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clase", "Clase")
                        .WithMany("Reservas")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.HasOne("Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Salas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Domain.Entities.Membresia", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Navigation("Membresias");
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Navigation("Clases");
                });

            modelBuilder.Entity("Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("Clases");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("Domain.Entities.Alumno", b =>
                {
                    b.Navigation("Membresias");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Clases");
                });
#pragma warning restore 612, 618
        }
    }
}
